### ISSUE TITLE
Issue in /src/pages/support/faq.md

### ISSUE THREAD

**Issue by ackoch** [AdobeDocs/adobe-io-runtime#101]
I think this is no longer valid: 

Usage Quotas
What usage quotas are in place for Adobe I/O Runtime?
There are presently no usage quotas on Adobe I/O Runtime.

The page 

https://helpx.adobe.com/legal/product-descriptions/adobe-developer-app-builder.html 

actually does define a quota.

**Comment by shazron** [comment]
fixed via 64028d6550ff85f0fad9f935b7fbe43801b99dda
