### ISSUE TITLE
Issue in /src/pages/guides/tools/cli_install.md

### ISSUE THREAD

**Issue by sgovindu88** [AdobeDocs/adobe-io-runtime#116]

**Comment by sgovindu88** [comment]
<img width="836" alt="Screenshot 2024-02-12 at 11 48 58 PM" src="https://github.com/AdobeDocs/adobe-io-runtime/assets/101291692/eab2fb81-4666-4877-8bf3-39f6a4c853a7">

**Comment by purplecabbage** [comment]
You need to have sufficient permissions on your machine to install npm packages globally
https://stackoverflow.com/questions/48910876/error-eacces-permission-denied-access-usr-local-lib-node-modules
