### ISSUE TITLE
Add support for Node 22

### ISSUE THREAD

**Issue by thedoc31** [AdobeDocs/adobe-io-runtime#138]
Node.js 20 will exit "Active" status in late 2024, transitioning into the "Maintenance" phase. Because development will no longer occur there [1], please add support for Node 22. 

[1]
https://nodejs.org/en/about/previous-releases

**Comment by shazron** [comment]
`nodejs:22` kind support is already online, but we haven't updated the docs yet.
```
curl https://adobeioruntime.net
```

Fix notes: see https://github.com/AdobeDocs/adobe-io-runtime/commit/6e8faec358db9d457cba518f1e3ff8059974f73f#diff-41177f625ac972d7edc42876f1f84f69d30e8014892e6c4a3cd579bf77ea5f8fR3

**Comment by shazron** [comment]
No, that note was for the dev that will fix this, pointing them to the actual location.
