### ISSUE TITLE
Minor issue with the curl command in creating_actions.md

### ISSUE THREAD

**Issue by arjuncooliitr** [AdobeDocs/adobe-io-runtime#28]
### Expected Behaviour
Curl command listed on this page to invoke web actions should execute successfully.

### Actual Behaviour
Running curl command as listed on this page gives error: 
`curl: (5) Could not resolve proxy: GET`
### Reproduce Scenario (including but not limited to)
Create and invoke any web action using curl command as listed on the page.

**Comment by shazron** [comment]
fixed in #29
