### ISSUE TITLE
Default version

### ISSUE THREAD

**Issue by ackoch** [AdobeDocs/adobe-io-runtime#63]
Issue in /src/pages/support/faq.md

According to https://developer.adobe.com/runtime/docs/guides/reference/runtimes/#nodejs-v14
"Node v16 is the default image" (not 14). 

Not sure which statement is correct

**Comment by larsroettig** [comment]
Is updated can you pls close it https://github.com/AdobeDocs/adobe-io-runtime/blob/main/src/pages/support/faq.md
